trigger: none
pr: none

variables:
  GAZEBO_BUILD_WORKING_DIRECTORY: $(Build.SourcesDirectory)\gazebo\gazebo9
  GAZEBO_INSTALL_PREFIX: 'c:\opt\rosdeps\x64'
  GAZEBO_CMAKE_BUILD_TYPE: 'RelWithDebInfo'
  GAZEBO_CMAKE_PDB_OUTPUT_DIRECTORY: '$(Build.ArtifactStagingDirectory)\symbols'

jobs:
- job: Build
  timeoutInMinutes: 240
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      choco upgrade 7zip
      choco upgrade pkg-config boost freeimage protobuf qt5-sdk dlfcn-win32 libcurl ogre zeromq cppzmq tbb qwt tinyxml2
    displayName: Install system dependencies
  - script: |
      git clone https://github.com/yaml/libyaml -b 0.2.5
      git clone https://github.com/open-source-parsers/jsoncpp -b 1.9.3
      git clone https://github.com/nih-at/libzip -b v1.7.1
      git clone https://github.com/ignitionrobotics/ign-cmake -b ignition-cmake2_2.2.0
      git clone https://github.com/ignitionrobotics/ign-math -b ignition-math6_6.4.0
      git clone https://github.com/ignitionrobotics/ign-msgs -b ignition-msgs5_5.3.0
      git clone https://github.com/ignitionrobotics/ign-common -b ignition-common3_3.6.0
      git clone https://github.com/ignitionrobotics/ign-fuel-tools -b ignition-fuel-tools4_4.1.0
      git clone https://github.com/ignitionrobotics/ign-transport -b ignition-transport8_8.0.0
      git clone https://github.com/osrf/sdformat -b sdformat9_9.2.0
      git clone https://github.com/ms-iot/gazebo -b windows/gazebo11_11.0.0
    displayName: Get sources
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      call "build.bat" libyaml
    displayName: libyaml
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      call "build.bat" jsoncpp
    displayName: jsoncpp
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      call "build.bat" libzip
    displayName: libzip
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      call "build.bat" ign-cmake
    displayName: ign-cmake
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      call "build.bat" ign-math
    displayName: ign-math
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      call "build.bat" ign-common
    displayName: ign-common
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      call "build.bat" ign-msgs
    displayName: ign-msgs
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      call "build.bat" ign-fuel-tools
    displayName: ign-fuel-tools
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      call "build.bat" ign-transport
    displayName: ign-transport
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      call "build.bat" sdformat
    displayName: sdformat
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      call "build.bat" gazebo
    displayName: gazebo
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - script: |
      powershell.exe -noexit -file "copy_binaries.ps1"
    displayName: Copy binaries
    workingDirectory: $(GAZEBO_BUILD_WORKING_DIRECTORY)
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'opt'
